### ISSUE TITLE
is it possible to remove rows from a MeasurementSet (ms) table ?

### ISSUE THREAD

**Issue by satya-yuga** [casacore/python-casacore#153]
help needed
Hello there!
I need to remove some rows from a MS table.
I tried to employ `table.removerows(few_rows)` but I got an error related to "storage managers" (?).
Then I did read that it only works for reference tables.
Later I tried to select (TaQL) the desired rows in order to save them, but it didn't work.
How could I actually remove rows from a MS table?
Greetings,

**Comment by gervandiepen** [comment]
It depends on the storage manager(s) used if a row can be deleted. Some
(e.g., StandardStMan) support it, some (e.g., TiledStMan) do not (because
it is impossible). In general the TiledStMan is used for some columns of
the MeasurementSet making it impossible to remove rows from an MS.
What you can do is selecting the rows you want to process and use the
resulting (reference) table as the input for the program you want to use.
Alternatively, you can make a deep copy of the selection (using e.g.
'giving new.ms as plain') in the TaQL command.

**Comment by satya-yuga** [comment]
The "GIVING" stuff worked perfectly.
Thank you very much!
