### ISSUE TITLE
multi-mms reading

### ISSUE THREAD

**Issue by miguelcarcamov** [casacore/python-casacore#221]
Hi everyone, 

I want to implement a multi-mms reader using python-casacore. Also, I want to convert a normal MS to MMS in my python framework. It is possible to this with python-casacore and not using the CASA partition function? What would be the difference between reading a table or using taql queries if the input measurement set is normal or multi-mms? It is possible to read a mms file using python-casacore?

Regards,

**Comment by gervandiepen** [comment]
Hi Miguel,

I understand you want to partition an MS into multiple parts (e.g., by
spectral window) and thereafter virtually concatenate them into an MMS.
You can do the split with taql using a query per part like
     select from main.ms where DATA_DESC_ID=1 giving part1.ms
In this way it creates a reference table (i.e., it only contains the row
numbers in the original MS). The advantage is that it is very fast, but you
still have to keep the original. Furthermore, the main drawback is that
writing into the various parts in parallel is not really possible because
all parts access the original MS. It will require locking.
But when doing
     select from main.ms where DATA_DESC_ID=1 giving part1.ms as plain
you create a copy for each part which will take more time.
Of course, you can also do it in python-casacore like
    ms=pt.table('main.ms')
    for t in ms.iter('DATA_DESC_ID'):

**Comment by gervandiepen** [comment]
Sorry. Touched the sent button too early.

# Split the MS by iterating over the spectral windows
ms=pt.table('main.ms')
nr=0
names=[]
for t in ms.iter('DATA_DESC_ID'):
    name='part%d.ms'%nr
    t.rename(name)
    nr+=1
    names.append(name)
ms.close()
# Concatenate all parts into an MMS
t=table(names)
t.rename('my.mms')


Using python-casacore is a bit easier than using taql, because you can use
iteration. For taql you have to know all spectral windows.

An MMS is seen as an ordinary table, so you can use all tools (such as
taql) on it.
In taql you can also concatenate to create an MMS like
    select from ['part1.ms','part2.ms'] giving 'my.mms'

I hope I've made no mistakes. I did not test it.
Cheers, Ger

**Comment by miguelcarcamov** [comment]
yes, this is exactly what I am looking for. A way to partition the measurement set so my program can read big datasets. Although I found a really useful tool for it (dask-ms) which uses python-casacore too :)
