### ISSUE TITLE
How to create images with pixel values that have different data types than float32?

### ISSUE THREAD

**Issue by dmehring** [casacore/python-casacore#250]
To create a new image https://casacore.github.io/python-casacore/casacore_images.html says to use casacore.images.image(imagename="myimage.im", shape=myshape)

This appears to create an image with pixels that have data type float32. Is there a way to create an image with pixels of other data types? Specifying the values parameter is problematic when creating large images where the data array may exhaust the system memory. ATM I'm interested in creating an image with complex64 valued pixels.
Thanks

**Comment by tammojan** [comment]
I don't think this is currently possible.

It could be implemented quite easy in ImageProxy, making a variant of [this function](https://github.com/casacore/casacore/blob/master/images/Images/ImageProxy.cc#L99) that takes only a shape. Apparently it would need a new number of arguments to get the boost-python bindings correct, when making a new wrapper [around here](https://github.com/casacore/python-casacore/blob/e484d657aad6c123c525bda472809cbb64c47dec/src/pyimages.cc#L57) in python-casacore.

Alternatively, you could initialize with a small data array, and then resize the Image. However, unfortunately the function `resize` is not made available in ImageInterface. So that would also require an addition to both casacore and python-casacore.

**Comment by dmehring** [comment]
It actually does look like you can do this as is, by setting the shape parameter *and* setting the values parameter equal to a value of the data type you want the pixel values to be.

So
casacore.images.image(imagename="myimage.im", shape=myshape, values=0+0j)
appears to do what I want.
